//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApplication.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add T3Rb.
        /// </summary>
        public static string AddT3RbRowButton {
            get {
                return ResourceManager.GetString("AddT3RbRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TTbC ROW.
        /// </summary>
        public static string AddTTbCRowButton {
            get {
                return ResourceManager.GetString("AddTTbCRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TTC ROW.
        /// </summary>
        public static string AddTTcRowButton {
            get {
                return ResourceManager.GetString("AddTTcRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Clock.
        /// </summary>
        public static string AlarmClock {
            get {
                return ResourceManager.GetString("AlarmClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C = Checkbox.
        /// </summary>
        public static string CDescription {
            get {
                return ResourceManager.GetString("CDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column 1.
        /// </summary>
        public static string Column1Header {
            get {
                return ResourceManager.GetString("Column1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column 2.
        /// </summary>
        public static string Column2Header {
            get {
                return ResourceManager.GetString("Column2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column 3.
        /// </summary>
        public static string Column3Header {
            get {
                return ResourceManager.GetString("Column3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string DeleteRowButton {
            get {
                return ResourceManager.GetString("DeleteRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Door.
        /// </summary>
        public static string FrontDoor {
            get {
                return ResourceManager.GetString("FrontDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rb = Radio Button.
        /// </summary>
        public static string RbDescription {
            get {
                return ResourceManager.GetString("RbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Type.
        /// </summary>
        public static string RowHeader {
            get {
                return ResourceManager.GetString("RowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Level.
        /// </summary>
        public static string SecurityLevel {
            get {
                return ResourceManager.GetString("SecurityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T3Rb Row.
        /// </summary>
        public static string T3RbRowHeader {
            get {
                return ResourceManager.GetString("T3RbRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tb = Textbox.
        /// </summary>
        public static string TbDescription {
            get {
                return ResourceManager.GetString("TbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T = Text.
        /// </summary>
        public static string TDescription {
            get {
                return ResourceManager.GetString("TDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTbC Row.
        /// </summary>
        public static string TTbCRowHeader {
            get {
                return ResourceManager.GetString("TTbCRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTC Row.
        /// </summary>
        public static string TTCRowHeader {
            get {
                return ResourceManager.GetString("TTCRowHeader", resourceCulture);
            }
        }
    }
}
